export default {
  guide: "Guide",
  signup: "Signup",
  signin: "Signin",
  forgetpassword: "ForgetPassword",
  confirmation: "Confirmation",
  newPassword: "NewPassword",
  home: "Home",
  bussiness: "Bussiness",
  calendar: "Calendar",
  search: "Search",
  profile: "Profile",
  aboutus: "AboutUs",
  contactus: "ContactUs",
  editprofile: "EditProfile",
  reservation:"Reservation",
  reservItem:"ReservItem",
  savedBusiness:"SaveBusiness",
  invoices:"Invoices",
  payment:"Payment",
  review:"Review",
  addCard:"AddCard",
  singleBussines:"SingleBussines",
  selectBookTime:"SelectBookTime",
  booking:"Booking",
  searchOnMap:"SearchOnMap",
  monthCalendar:"MonthCalendar",
  yearCalendar:"YearCalendar",
  dayCalendar:"DayCalendar",
};
